apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  serviceName: postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres
          imagePullPolicy: IfNotPresent
          envFrom: 
            - configMapRef:
                name: postgres-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
          - name: postgres-data
            mountPath: "/var/lib/postgresql/data"
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi